name: Sync GitHub Issue to Jira

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

jobs:
  sync-to-jira:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      # BUSCA: Tenta encontrar um card que já tenha o link desta Issue na descrição
      - name: Find Existing Issue
        id: find
        uses: atlassian/gajira-find-issue-key@v3
        with:
          string: '${{ github.event.issue.html_url }}' # Busca pelo link único da Issue

      # CRIAÇÃO: Só roda se for uma Issue NOVA e o "find" não achou nada
      - name: Create Issue in Jira
        if: github.event_name == 'issues' && github.event.action == 'opened' && steps.find.outputs.issue == ''
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: 'HUBFUP' 
          issuetype: 'Task'
          summary: '${{ github.event.issue.title }}'
          description: 'Issue original no GitHub: ${{ github.event.issue.html_url }}\n\n${{ github.event.issue.body }}'

      # ATUALIZAÇÃO: Se a issue foi editada E o "find" achou o card, ele atualiza o título
      - name: Update Jira Issue
        if: github.event_name == 'issues' && github.event.action == 'edited' && steps.find.outputs.issue != ''
        uses: atlassian/gajira-edit@v3
        with:
          issue: ${{ steps.find.outputs.issue }}
          summary: '${{ github.event.issue.title }}'
          description: 'Issue original no GitHub: ${{ github.event.issue.html_url }}\n\n${{ github.event.issue.body }}'

      # COMENTÁRIO: Roda se for um comentário e o "find" achou o card
      - name: Add Comment to Jira
        if: github.event_name == 'issue_comment' && steps.find.outputs.issue != ''
        uses: atlassian/gajira-comment@v3
        with:
          issue: ${{ steps.find.outputs.issue }}
          comment: "${{ github.event.comment.user.login }} comentou no GitHub: \n\n ${{ github.event.comment.body }}"
